sudo: required
dist: trusty
language: node_js
node_js:
  - '6.11.5'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

script: ng test --single-run